(()=>{'use strict';
const cfg=window.WRYTOLE_CONFIG||{},$=id=>document.getElementById(id);
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s).toLocaleString():'—',money=n=>'UGX '+Number(n||0).toLocaleString('en-UG');
function alertMsg(s,bad=false){const e=$('admin-alert');e.textContent=s;e.classList.remove('hidden');e.style.background=bad?'#ffe6e6':'#e4f6eb';e.style.color=bad?'#8d1717':'#125b35'}
function hideAlert(){$('admin-alert').classList.add('hidden')}
function theme(){if(localStorage.getItem('wrytole-theme')==='dark')document.body.classList.add('dark');$('theme')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('wrytole-theme',document.body.classList.contains('dark')?'dark':'light')})}
function table(rows,heads,render){if(!rows?.length)return '<p class="admin-muted">Nothing to show yet.</p>';return `<table class="admin-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(render).join('')}</tbody></table>`}
async function adminGuard(){const {data:{session}}=await sb.auth.getSession();if(!session){showLogin();return false}const {data:p,error}=await sb.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(error||p?.role!=='admin'){await sb.auth.signOut();showLogin();alertMsg('This account is not authorized as an administrator. The admin role must be assigned securely in Supabase.',true);return false} $('admin-login').classList.add('hidden');$('admin-content').classList.remove('hidden');$('admin-signout').classList.remove('hidden');return true}
function showLogin(){$('admin-login').classList.remove('hidden');$('admin-content').classList.add('hidden');$('admin-signout').classList.add('hidden')}
async function refresh(){hideAlert();try{const [a,p,s,r]=await Promise.all([
sb.from('teacher_applications').select('id,user_id,requested_role,school_name,status,notes,created_at').order('created_at',{ascending:false}).limit(100),
sb.from('payment_submissions').select('id,user_id,plan_id,amount_ugx,reference,payment_method,status,notes,created_at').order('created_at',{ascending:false}).limit(100),
sb.from('subscriptions').select('id,user_id,plan_id,status,starts_at,ends_at,downloads_used').order('ends_at',{ascending:false}).limit(100),
sb.from('resources').select('id,title,uploader_id,resource_type,level,subject_name,status,price_ugx,created_at').order('created_at',{ascending:false}).limit(150)
]);for(const x of [a,p,s,r])if(x.error)throw x.error;
const apps=a.data||[],payments=p.data||[],subs=s.data||[],resources=r.data||[];
$('stat-applications').textContent=apps.filter(x=>x.status==='pending').length;$('stat-payments').textContent=payments.filter(x=>!['approved','rejected'].includes(x.status)).length;$('stat-subs').textContent=subs.filter(x=>x.status==='active'&&new Date(x.ends_at)>new Date()).length;$('stat-resources').textContent=resources.length;
$('applications-table').innerHTML=table(apps,['Applicant ID','Requested role','School','Status','Submitted','Actions'],x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.requested_role)}</td><td>${esc(x.school_name||'—')}</td><td>${esc(x.status||'pending')}</td><td>${date(x.created_at)}</td><td><div class="admin-actions"><button data-app="${esc(x.id)}" data-status="approved">Approve</button><button data-app="${esc(x.id)}" data-status="rejected" class="danger">Reject</button></div></td></tr>`);
$('payments-table').innerHTML=table(payments,['User ID','Plan','Amount','Reference','Status','Submitted','Actions'],x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.plan_id)}</td><td>${money(x.amount_ugx)}</td><td>${esc(x.reference)}<br><small>${esc(x.notes||'')}</small></td><td>${esc(x.status||'pending')}</td><td>${date(x.created_at)}</td><td><div class="admin-actions"><button data-payment="${esc(x.id)}" data-status="approved">Verify & activate</button><button data-payment="${esc(x.id)}" data-status="rejected" class="danger">Reject</button></div></td></tr>`);
$('subscriptions-table').innerHTML=table(subs,['User ID','Plan','Status','Starts','Expires','Actions'],x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.plan_id)}</td><td>${esc(x.status)}</td><td>${date(x.starts_at)}</td><td>${date(x.ends_at)}</td><td><button data-sub="${esc(x.id)}" data-status="active">Set active</button><button data-sub="${esc(x.id)}" data-status="cancelled" class="danger">Cancel</button></td></tr>`);
$('resources-table').innerHTML=table(resources,['Title','Uploader ID','Type / class','Subject','Status','Price','Actions'],x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.uploader_id)}</td><td>${esc(x.resource_type)} · ${esc(x.level)}</td><td>${esc(x.subject_name||'—')}</td><td>${esc(x.status)}</td><td>${money(x.price_ugx)}</td><td><div class="admin-actions"><button data-resource="${esc(x.id)}" data-status="approved">Publish</button><button data-resource="${esc(x.id)}" data-status="pending">Unpublish</button><button data-resource="${esc(x.id)}" data-status="rejected" class="danger">Reject</button></div></td></tr>`);
}catch(e){alertMsg('Could not load admin data: '+(e.message||'Check database migration and admin RLS policies.'),true)}}
async function action(button){button.disabled=true;try{if(button.dataset.app){const {error}=await sb.from('teacher_applications').update({status:button.dataset.status}).eq('id',button.dataset.app);if(error)throw error;if(button.dataset.status==='approved'){const {data:app}=await sb.from('teacher_applications').select('user_id,requested_role').eq('id',button.dataset.app).single();if(app){const {error:e}=await sb.from('profiles').update({role:app.requested_role==='school'?'school':'teacher'}).eq('id',app.user_id);if(e)throw e}}}
else if(button.dataset.payment){const {data:pay,error}=await sb.from('payment_submissions').select('id,user_id,plan_id,amount_ugx,status').eq('id',button.dataset.payment).single();if(error)throw error;if(button.dataset.status==='approved'){const {data:plan,error:pe}=await sb.from('subscription_plans').select('duration_days').eq('id',pay.plan_id).single();if(pe)throw pe;const start=new Date(),end=new Date(start.getTime()+Number(plan.duration_days||30)*86400000);const {error:se}=await sb.from('subscriptions').insert({user_id:pay.user_id,plan_id:pay.plan_id,status:'active',starts_at:start.toISOString(),ends_at:end.toISOString(),downloads_used:0});if(se)throw se}const {error:ue}=await sb.from('payment_submissions').update({status:button.dataset.status}).eq('id',pay.id);if(ue)throw ue}
else if(button.dataset.sub){const {error}=await sb.from('subscriptions').update({status:button.dataset.status}).eq('id',button.dataset.sub);if(error)throw error}
else if(button.dataset.resource){const {error}=await sb.from('resources').update({status:button.dataset.status}).eq('id',button.dataset.resource);if(error)throw error}
alertMsg('Change saved.');await refresh()}catch(e){alertMsg('Action failed: '+(e.message||'Database policy rejected the change.'),true)}finally{button.disabled=false}}
document.addEventListener('DOMContentLoaded',async()=>{theme();if(!sb){alertMsg('Supabase configuration is missing. Check app-config.js.',true);return}
$('admin-login-form').addEventListener('submit',async e=>{e.preventDefault();hideAlert();const {error}=await sb.auth.signInWithPassword({email:$('admin-email').value.trim(),password:$('admin-password').value});if(error){alertMsg(error.message,true);return}if(await adminGuard())await refresh()});
$('admin-signout').addEventListener('click',async()=>{await sb.auth.signOut();showLogin()});
document.querySelectorAll('[data-refresh]').forEach(b=>b.addEventListener('click',refresh));
document.body.addEventListener('click',e=>{const b=e.target.closest('button[data-app],button[data-payment],button[data-sub],button[data-resource]');if(b)action(b)});
if(await adminGuard())await refresh()});
})();