(() => {
const URL="https://ifclmosdzakxxklqiiaa.supabase.co";
const KEY="sb_publishable_Ms0VZ5ks6yO3eCvuACj-KA_CiLUmPbD";
const $=id=>document.getElementById(id), sb=window.supabase?.createClient(URL,KEY);
let rows=[], userProfile=null, mode="signin", timer;
$("year").textContent=new Date().getFullYear();
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("toast").classList.remove("show"),2800)}
function message(s){$("message").textContent=s;$("message").classList.remove("hidden")}
function openAuth(){$("message").classList.add("hidden");$("auth").showModal()}
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$ (b.dataset.close).close());
["join","join2","educator"].forEach(id=>$(id).onclick=openAuth);
$("account").onclick=()=>userProfile? $("profile").showModal():openAuth();
$("mobile-account").onclick=$("account").onclick;
$("theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("wrytole-theme",document.body.classList.contains("dark")?"dark":"light")};
if(localStorage.getItem("wrytole-theme")==="dark")document.body.classList.add("dark");
$("switch").onclick=()=>{mode=mode==="signin"?"signup":"signin";$("auth-heading").textContent=mode==="signin"?"Your learning journey starts here.":"Create your learning account.";$("auth-description").textContent=mode==="signin"?"Sign in to access your account.":"Create an account to get started.";$("email-submit").textContent=mode==="signin"?"Sign in with email":"Create account";$("switch").textContent=mode==="signin"?"New here? Create an account":"Already registered? Sign in"};
$("google").onclick=async()=>{if(!sb)return message("Authentication unavailable.");let {error}=await sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+location.pathname}});if(error)message(error.message)};
$("email-form").onsubmit=async e=>{e.preventDefault();if(!sb)return message("Authentication unavailable.");let email=$("email").value.trim(),password=$("password").value;try{let res=mode==="signin"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(res.error)throw res.error;if(mode==="signup"){message("Account request submitted. Check your email if confirmation is enabled.");return}$("auth").close();await session();toast("Signed in successfully.")}catch(err){message(err.message||"Unable to sign in.")}};
$("signout").onclick=async()=>{if(sb)await sb.auth.signOut();userProfile=null;updateProfile();$("profile").close();toast("Signed out.")};
$("dashboard").onclick=()=>{ $("profile").close();toast(userProfile?.role==="admin"?"Admin role recognised; secure admin actions still need implementation.":"Your account is active. Uploads and paid access are not enabled yet.") };
function updateProfile(){ $("account").textContent=userProfile?"My account":"Sign in";if(userProfile){$("profile-name").textContent=userProfile.full_name||"Welcome";$("profile-email").textContent=userProfile.email||"";$("profile-role").textContent=(userProfile.role||"student").toUpperCase()} }
async function session(){if(!sb)return;let {data}=await sb.auth.getSession();if(!data.session){userProfile=null;updateProfile();return}let u=data.session.user;let {data:r}=await sb.from("profiles").select("full_name,role,school_name").eq("id",u.id).maybeSingle();userProfile={...r,email:u.email};updateProfile()}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const icons={paper:"📄",notes:"📘",worksheet:"✏️",lesson:"🎓",video:"▶️",other:"📚"};
function filtered(){let q=$("q").value.toLowerCase().trim(),l=$("level").value,t=$("type").value,s=$("subject").value;return rows.filter(r=>(!q||[r.title,r.description,r.subject_name,r.topic,r.class_name,r.level].join(" ").toLowerCase().includes(q))&&(!l||r.level===l)&&(!t||r.resource_type===t)&&(!s||r.subject_name===s))}
function render(){let list=filtered();$("count").textContent=list.length+" approved resource"+(list.length===1?"":"s");$("grid").innerHTML=list.map(r=>`<article class="resource"><div class="cover">${icons[r.resource_type]||"📚"}</div><div class="resource-body"><span class="tag">${esc(r.resource_type)} · ${esc(r.level)}</span><h3>${esc(r.title)}</h3><p>${esc(r.description||[r.subject_name,r.class_name,r.topic].filter(Boolean).join(" · ")||"Learning material shared with the community.")}</p><div class="resource-foot"><b>${Number(r.price_ugx||0)>0?"UGX "+Number(r.price_ugx).toLocaleString("en-UG"):"Free resource"}</b><button data-id="${esc(r.id)}">View ↗</button></div></div></article>`).join("");$("empty").classList.toggle("hidden",list.length>0);$("grid").classList.toggle("hidden",list.length===0);$("grid").querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{let r=rows.find(x=>x.id===b.dataset.id);if(!userProfile){toast("Sign in to continue.");openAuth()}else if(Number(r.price_ugx)>0)toast("Secure checkout is not enabled yet.");else if(r.external_video_url)window.open(r.external_video_url,"_blank","noopener,noreferrer");else if(r.file_path)toast("Secure download authorization is not enabled yet.");else toast("No file is attached to this resource yet.")})}
async function load(){if(!sb){$("count").textContent="Resource service unavailable";return}let {data,error}=await sb.from("resources").select("id,title,description,resource_type,level,class_name,subject_name,topic,price_ugx,file_path,external_video_url,status,created_at").eq("status","approved").order("created_at",{ascending:false}).limit(60);if(error){$("count").textContent="Approved resources will appear after database access is configured.";return}rows=data||[];let subs=[...new Set(rows.map(r=>r.subject_name).filter(Boolean))].sort();$("subject").innerHTML='<option value="">All subjects</option>'+subs.map(s=>`<option>${esc(s)}</option>`).join("");render()}
["q"].forEach(id=>$(id).addEventListener("input",render));["level","type","subject"].forEach(id=>$(id).addEventListener("change",render));$("refresh").onclick=load;$("clear").onclick=()=>{$("q").value=$("level").value=$("type").value=$("subject").value="";render()};
if(sb)sb.auth.onAuthStateChange(()=>setTimeout(session,0));session();load();
})();